name: Generate Release Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore my-upload-key.jks \
            -storepass "${{ secrets.STORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}" \
            -alias upload \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Aura Browser, O=Aura Browser, C=ID"

      - name: Encode keystore
        run: |
          base64 -w 0 my-upload-key.jks > keystore.base64

      - name: Upload keystore artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-keystore
          path: keystore.base64
